#!/usr/bin/env ruby

PROJECT_ROOT_DIR = `git rev-parse --show-toplevel`.chomp

$LOAD_PATH << "#{PROJECT_ROOT_DIR}/lib"

require "dockerfolder"

if __FILE__ == $PROGRAM_NAME
  Dockerfolder.run(ARGV)
end
